dependencies:
  - nbserverproxy
  - tornado>6
  - intake::intake
  - pyviz/label/dev::geoviews-core=1.6.2
  - pyviz/label/dev::holoviews=1.12.2
  - pyviz/label/dev::hvplot=0.4.0
  - pyviz/label/dev::panel=0.5.1
  - bokeh::bokeh=1.1.0
  - pandas>=0.23.4
  - xarray
  - netcdf4